#ifndef MYACTUATOR_HARDWARE_INTERFACE__VISIBILITY_CONTROL_HPP_
#define MYACTUATOR_HARDWARE_INTERFACE__VISIBILITY_CONTROL_HPP_

// This logic was borrowed (then namespaced) from the examples on the gcc wiki:
//     https://gcc.gnu.org/wiki/Visibility

#if defined _WIN32 || defined __CYGWIN__
#ifdef __GNUC__
#define MYACTUATOR_HARDWARE_INTERFACE_EXPORT __attribute__((dllexport))
#define MYACTUATOR_HARDWARE_INTERFACE_IMPORT __attribute__((dllimport))
#else
#define MYACTUATOR_HARDWARE_INTERFACE_EXPORT __declspec(dllexport)
#define MYACTUATOR_HARDWARE_INTERFACE_IMPORT __declspec(dllimport)
#endif
#ifdef MYACTUATOR_HARDWARE_INTERFACE_BUILDING_LIBRARY
#define MYACTUATOR_HARDWARE_INTERFACE_PUBLIC MYACTUATOR_HARDWARE_INTERFACE_EXPORT
#else
#define MYACTUATOR_HARDWARE_INTERFACE_PUBLIC MYACTUATOR_HARDWARE_INTERFACE_IMPORT
#endif
#define MYACTUATOR_HARDWARE_INTERFACE_PUBLIC_TYPE MYACTUATOR_HARDWARE_INTERFACE_PUBLIC
#define MYACTUATOR_HARDWARE_INTERFACE_LOCAL
#else
#define MYACTUATOR_HARDWARE_INTERFACE_EXPORT __attribute__((visibility("default")))
#define MYACTUATOR_HARDWARE_INTERFACE_IMPORT
#if __GNUC__ >= 4
#define MYACTUATOR_HARDWARE_INTERFACE_PUBLIC __attribute__((visibility("default")))
#define MYACTUATOR_HARDWARE_INTERFACE_LOCAL __attribute__((visibility("hidden")))
#else
#define MYACTUATOR_HARDWARE_INTERFACE_PUBLIC
#define MYACTUATOR_HARDWARE_INTERFACE_LOCAL
#endif
#define MYACTUATOR_HARDWARE_INTERFACE_PUBLIC_TYPE
#endif

#endif  // MYACTUATOR_HARDWARE_INTERFACE__VISIBILITY_CONTROL_HPP_
