controller_manager:
  ros__parameters:
    update_rate: 100  # Hz
    
    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

    motor_controller:
      type: forward_command_controller/ForwardCommandController
    
    motor_broadcaster:
      type: myactuator_state_broadcaster/MyActuatorStateBroadcaster
    

motor_controller:
  ros__parameters:
    joints:
      - body_shaft_joint
    interface_name: position
