controller_manager:
  ros__parameters:
    update_rate: 100  # Hz

    forward_position_controller:
      type: position_controllers/JointGroupPositionController

    forward_velocity_controller:
      type: velocity_controllers/JointGroupVelocityController

    forward_effort_controller:
      type: effort_controllers/JointGroupEffortController
      
    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

forward_position_controller:
  ros__parameters:
    joints:
      - joint1
      - joint2

forward_velocity_controller:
  ros__parameters:
    joints:
      - joint1
      - joint2

forward_effort_controller:
  ros__parameters:
    joints:
      - joint1
      - joint2