#ifndef MYACTUATOR_STATE_BROADCASTER__MYACTUATOR_STATE_BROADCASTER_HPP_
#define MYACTUATOR_STATE_BROADCASTER__MYACTUATOR_STATE_BROADCASTER_HPP_

#include <memory>
#include <string>
#include <unordered_map>
#include <vector>

#include "control_msgs/msg/dynamic_joint_state.hpp"
#include "controller_interface/controller_interface.hpp"
#include "myactuator_state_broadcaster/visibility_control.h"
// auto-generated by generate_parameter_library
#include "myactuator_state_broadcaster_parameters.hpp"
#include "rclcpp_lifecycle/lifecycle_publisher.hpp"
#include "rclcpp_lifecycle/node_interfaces/lifecycle_node_interface.hpp"
#include "realtime_tools/realtime_publisher.h"
#include "myactuator_interfaces/msg/motor_status.hpp"
#include "semantic_components/semantic_component_interface.hpp"

namespace myactuator_state_broadcaster
{
class MyActuatorStateBroadcaster : public controller_interface::ControllerInterface
{
public:
  MYACTUATOR_STATE_BROADCASTER_PUBLIC
  MyActuatorStateBroadcaster();

  MYACTUATOR_STATE_BROADCASTER_PUBLIC
  controller_interface::InterfaceConfiguration command_interface_configuration() const override;

  MYACTUATOR_STATE_BROADCASTER_PUBLIC
  controller_interface::InterfaceConfiguration state_interface_configuration() const override;

  MYACTUATOR_STATE_BROADCASTER_PUBLIC
  controller_interface::return_type update(
    const rclcpp::Time & time, const rclcpp::Duration & period) override;

  MYACTUATOR_STATE_BROADCASTER_PUBLIC
  controller_interface::CallbackReturn on_init() override;

  MYACTUATOR_STATE_BROADCASTER_PUBLIC
  controller_interface::CallbackReturn on_configure(
    const rclcpp_lifecycle::State & previous_state) override;

  MYACTUATOR_STATE_BROADCASTER_PUBLIC
  controller_interface::CallbackReturn on_activate(
    const rclcpp_lifecycle::State & previous_state) override;

  MYACTUATOR_STATE_BROADCASTER_PUBLIC
  controller_interface::CallbackReturn on_deactivate(
    const rclcpp_lifecycle::State & previous_state) override;

protected:
  bool init_joint_data();
  void init_joint_state_msg();
  bool use_all_available_interfaces() const;

protected:
  // Optional parameters
  std::shared_ptr<ParamListener> param_listener_;
  Params params_;
  std::unordered_map<std::string, std::string> map_interface_to_joint_state_;
  std::unordered_map<std::string, std::unordered_map<std::string, double>> name_if_value_mapping_;
  std::vector<std::string> joint_names_;

  std::shared_ptr<rclcpp::Publisher<myactuator_interfaces::msg::MotorStatus>> motor_state_publisher_;
  std::shared_ptr<realtime_tools::RealtimePublisher<myactuator_interfaces::msg::MotorStatus>> realtime_motor_state_publisher_;
};

}  // namespace myactuator_state_broadcaster

#endif  // MYACTUATOR_STATE_BROADCASTER__MYACTUATOR_STATE_BROADCASTER_HPP_